version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_HOST: "localhost"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "technostrelka_pg"
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ./.env
    ports:
      - 5444:5444
  